[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = "Advent of Code"
authors = ["Advait Hasabnis <advait.iitb@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^5.5.0"
isort = "^5.7.0"
black = "^20.8b1"

[tool.poetry.scripts]
puzzle = "advent_of_code.puzzle:main"

[tool.isort]
profile = "black"

[tool.black]
line-length = 99
skip-string-normalization = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
